FROM cnfldemos/cp-server-connect-datagen:0.5.0-6.2.0
RUN   confluent-hub install --no-prompt hpgrahsl/kafka-connect-mongodb:1.1.0 \
   && confluent-hub install --no-prompt microsoft/kafka-connect-iothub:0.6 \
   && confluent-hub install --no-prompt wepay/kafka-connect-bigquery:1.1.0 \
   && confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest \
   && confluent-hub install --no-prompt debezium/debezium-connector-sqlserver:latest

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"
ARG JDBC_JAR_LOCATION="/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib"
ARG MYSQL_CONNECTOR_VERSION="8.0.22"
RUN curl -k -SL "https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_CONNECTOR_VERSION}/mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar" \
    -o "${JDBC_JAR_LOCATION}/mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar"